django_store/django_store/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods_app.urls', namespace='goods_app')),
]

django_store/goods_app/urls.py
from django.urls import path

from . import views

app_name = 'goods_app'

urlpatterns = [
    path('', views.all_goods, name='all_goods'),
    path('<slug:category_slug>/', views.category_list, name='category_list'),
]

django_store/goods_app/models.py
from django.db import models
from django.db.models import Manager

from django.urls import reverse
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('goods_app:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class GoodItems(models.Model):
    UNITS = (
        (1, 'шт.'),
        (2, 'кг.'),
    )

    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Название товара', max_length=255)
    created_at = models.DateTimeField(verbose_name='Дата поступления', auto_created=True, auto_now_add=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=4, decimal_places=2)
    unit = models.PositiveIntegerField(verbose_name='Еденица измерения', choices=UNITS)
    slug = models.SlugField(max_length=255)
    supplier = models.CharField(verbose_name='Имя поставщика', max_length=255)
    sites = models.ManyToManyField(Site)
    object = Manager()
    on_site = CurrentSiteManager('sites')

    class Meta:
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.title

django_store/goods_app/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, GoodItems


def categories(request):
    return {
        'categories': Category.objects.all()
    }


def all_goods(request):
    goods = GoodItems.on_site.all()
    return render(request, 'goods_app/home.html', {'goods': goods})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    goods = GoodItems.on_site.select_related('category').filter(category=category)
    return render(request, 'goods_app/category.html', {'category': category, 'goods': goods})

django_store/templates/goods_app/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Section
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'goods_app:all_goods' %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

django_store/templates/goods_app/category.html
{% extends "./base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Goods{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in goods %}

        <div class="col">
          <div class="card shadow-sm">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

django_store/templates/goods_app/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

<table class="table">
    <tr>
        <th>Название</th>
        <th>Дата поступления</th>
        <th>Еденица измерения</th>
        <th>Имя поставщика</th>
        <th>Цена</th>
    </tr>
    {% for object in goods %}
        <tr>
            <td>{{ object.title }}</td>
            <td>{{ object.created_at }}</td>
            <td>{{ object.unit }}</td>
            <td>{{ object.supplier }}</td>
            <td>{{ object.price }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock %}

django_store/templates/goods_list.html
{% extends "base.html" %}

{% block content %}
<table class="table">
    <tr>
        <th>Название</th>
        <th>Дата поступления</th>
        <th>Еденица измерения</th>
        <th>Имя поставщика</th>
        <th>Цена</th>
    </tr>
    {% for object in object_list %}
        <tr>
            <td>{{ object.title }}</td>
            <td>{{ object.created_at }}</td>
            <td>{{ object.unit }}</td>
            <td>{{ object.supplier }}</td>
            <td>{{ object.price }}</td>
        </tr>
    {% endfor %}
</table>
<a href="" class="btn btn-success">Добавить</a>
{% endblock %}